a = 1+1;
println(a);
cad.setLineType("solid");
cad.setLineThickness(1);
cad.setColor("Green");
cad.line(0,0,0,10,5,2);
cad.disp();
sp[] = { 10,0,0 };
mp[] = { 15,5,0 };
ep[] = { 20,5,10 };
cad.setColor("Red");
cad.setLineType("dash");
cad.setLineThickness(5);
cad.line(sp[],ep[]);
cp[] = {10,5,5};
r = 5;
cad.setColor("Green");
cad.setLineType("phantom");
cad.setLineThickness(1);
cad.setFace("top");
cad.arc(cp[], r, 0, PI);
cad.setColor("Magenta");
cad.circle(sp[],mp[],ep[]);
cad.disp();
cad.init();